const express = require('express')
const router = express.Router()
const {UserController, ProductController, CartController} = require('../controllers')
const authentication = require('../middlewares/authentication')
const authorization = require('../middlewares/authorization')
const authorizationCustomer = require('../middlewares/authorizationCustomer')

router.post("/login", UserController.login)
router.post("/loginCustomer", UserController.loginCustomer)
router.post('/register', UserController.register)
router.get("/products", ProductController.getItem)
router.use(authentication)
router.get("/carts", authorizationCustomer, CartController.getCart)
router.post("/carts/:id", authorizationCustomer, CartController.addToCart)
router.put("/carts/:id", authorizationCustomer, CartController.putCart)
router.patch("/carts/:id", authorizationCustomer, CartController.patchCart)
router.delete("/carts/:id", authorizationCustomer, CartController.deleteCart)
router.post("/products", authorization, ProductController.addItem)
router.get("/products/:id", ProductController.getItemById)
router.put("/products/:id", authorization, ProductController.updateItem)
router.delete("/products/:id", authorization, ProductController.deleteItem)

module.exports = router